### PR TITLE
TST: Adding unit tests

### PR DESCRIPTION
**Pull request by Lucas-C**
I introduced the unit tests I originally developped in https://github.com/py-pdf/pypdf/pull/2170

I also added a `pytest -vv` execution as part of the GitHub Actions pipeline

### CODE REVIEW

**Comment by Lucas-C** [comment]
@MartinThoma: I think you added a dependency to `fpdf2` in https://github.com/py-pdf/pdfly/blob/main/pdfly/x2pdf.py#L6

But this dependency was not declared in https://github.com/py-pdf/pdfly/blob/main/pyproject.toml#L31

**Comment by MartinThoma** [comment]
@Lucas-C Thank you for the many improvements :pray: 

The PR looks awesome :tada: 

One last question before we merge it: Where do the images come from?

**Comment by Lucas-C** [comment]
The images come from https://github.com/py-pdf/fpdf2/tree/master/test/image/image_types:
* https://github.com/py-pdf/fpdf2/blob/master/test/image/image_types/insert_images_insert_jpg.jpg
* https://github.com/py-pdf/fpdf2/blob/master/test/image/image_types/pythonknight.png

**Comment by MartinThoma** [comment]
Very nice! Thank you :pray:

**Comment by Lucas-C** [comment]
Thank you!

Now I'll have to fix those `xfail-`ing tests...

We could also open issues with the `hacktoberfest` tag in order to invite contributors this month:
https://hacktoberfest.com/

**Comment by MartinThoma** [comment]
I like the idea of inviting new contributors :-) I would need to check what is required by us if we do that. I have no idea.

**Comment by Lucas-C** [comment]
> I like the idea of inviting new contributors :-) I would need to check what is required by us if we do that. I have no idea.

I added a few issues with the `hacktoberfest` tag:
https://github.com/py-pdf/pdfly/labels/hacktoberfest

**Pull request merged**
