### PR TITLE
Add booklet command

### PR DESCRIPTION
**Pull request by pastor-robert**
Add command "booklet". It reorders and 2-ups the pages to create a booklet. Booklets have a page count that is a multiple of four. If the input file's page count is not a multiple, blank pages, or user-specified pages, are inserted in fixed locations.

### CODE REVIEW

**Comment by Lucas-C** [comment]
Thank you very much for your contribution @pastor-robert 👍

We were already working on a `x2pdf --format` option that may overlap with your new subcommand: https://github.com/py-pdf/pdfly/issues/63

A PR is in progress: https://github.com/py-pdf/pdfly/pull/65
Could you maybe have a look at it? Wouldn't it cover a similar usage?

**Comment by pastor-robert** [comment]
> We were already working on a `x2pdf --format` option that may overlap with your new subcommand: #63

Thanks! I was very eager to get started, so I did not start a discussion or survey existing work. Mea culpa.

However, I don't see the overlap between these two. #63 is about specifying the output paper size of the x2 command. #77 produces an output file which, when printed and folded appropriately, creates a booklet.

This PR reorders pages into "signature order" or "book order".  Assuming an 8-page `input.pdf`, the following command sequences are equivalent.

```
pdfly booklet input.pdf output.pdf
```
```
pdfly cat -o tmp.pdf input.pdf 7 0 1 6 5 2 3 4 
pdfly up2 -o output.pdf tmp.pdf
```

If you are seeing an overlap that I'm missing, can you help me understand what that is?

**Comment by pastor-robert** [comment]
On the other hand, I could see an overlap between this PR and Issue #64 / PR #67.  Since the booklet feature is, in essence, a re-ordering and a 2-up, I can see some logic in putting this functionality in the 2-up subcommand. But, on the whole, booklet printing seems to me enough of its own unique behavior that it would be simpler for the user if it were its own subcommand.

**Comment by pastor-robert** [comment]
Thanks @Lucas-C . I went through about the same logic that you did. After I posted that note, I found #64 / #67. I thought about commands like `x2pdf --layout book-order input.pdf` or  `2-up --book-order input.pdf`,  but neither seemed to fit. 

My intuition is that end-users would be more confused by adding book-order printing to either of those features than they would be by having the feature stand alone. 

My recommendation is to make `booklet` stand apart from either `x2pdf` or `2-up`.

> Also, it seems that the booklet subcommand would extract pages from a single existing PDF, which would make it different from x2pdf behaviour...

I thought about having `booklet` subcommand take a set of PDF files & page ranges a la `cat`. I think that may be a good idea, but not for this initial version.

**Comment by Lucas-C** [comment]
Alright, you convinced me @pastor-robert 🙂

Merged!

Thank you very much for this excellent contribution 👍

**Comment by Lucas-C** [comment]
This has been released in version `0.4.0`: https://pypi.org/project/pdfly/#history

**Pull request merged**
