### PR TITLE
Fix 2-up printing

### PR DESCRIPTION
**Pull request by pastor-robert**
Fixed a call to `merge_translated_page`. Apparently, the switch from PyPDF2 to pypdf changed the signature of `merge_translated_page`, adding the `over` parameter. Change the call to use keyword parameters.

The symptom was 2-up only showed one page per sheet, on the left side, with blank space on the right.

### CODE REVIEW

**Comment by Lucas-C** [comment]
Hi @pastor-robert

Thank you very much for your contribution 👍

Could you maybe use this opportunity to add a unit test, by initatiating a `tests/test_up2.py` inspired by the other existing tests in the `tests/` directory?

**Comment by pastor-robert** [comment]
> Could you maybe use this opportunity to add a unit test, by initatiating a `tests/test_up2.py` inspired by the other existing tests in the `tests/` directory?

Sure. I'll do that tonight.

> Also, the GitHub Actions pipeline is failing, but just running `black pdfly/pdfly/up2.py` should solve it.

Thanks. I'll run `black`.

**Comment by Lucas-C** [comment]
Good job on this 👍

Thank you very much for your contribution!

**Comment by Lucas-C** [comment]
This has been released in version `0.4.0`: https://pypi.org/project/pdfly/#history

**Pull request merged**
